
# PostgreSQL

DROP TABLE IF EXISTS bot_config;

CREATE TABLE bot_config (
  id SERIAL PRIMARY KEY,
  prefix TEXT NOT NULL,
  owner SERIAL NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner) REFERENCES channels (id) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE (owner)
);