
# PostgreSQL

DROP TABLE IF EXISTS commands;

CREATE TABLE commands (
  id SERIAL PRIMARY KEY,
  command TEXT NOT NULL,
  description TEXT NOT NULL,
  function TEXT NOT NULL,
  owner SERIAL NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner) REFERENCES channels (id) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE (owner)
);